### ISSUE TITLE
pcs-0.12 support checklist

### ISSUE THREAD

**Issue by OndrejHome** [OndrejHome/ansible.pcs-modules-2#44]
For tracking what needs to be done to support pcs-0.12.
At time of creation of this issue there are some breaking changes from pcs-0.11.

Review the breaking changes in `man pcs` of version 0.12 - CHANGES IN PCS-0.12 - https://github.com/ClusterLabs/pcs/blob/main/pcs/pcs.8.in

Potentially relevant for modules here are at minimum:
- [x] `pcsd-status` -> `pcs pcsd status`
- [x] "Specifying  score  as  a  standalone value is deprecated in favor of score=value. "
- [x] `property list/show` -> `pcs property config`

**Comment by OndrejHome** [comment]
Most (if not all) changes needed for pcs-0.12 should be now available in modules here. Use tag `35.0.0` of this repository or tag `1.0.5` of ansible_collection.ha_cluster (https://github.com/OndrejHome/ansible_collection.ha_cluster). Closing this for now.
